#cloud-config
package_upgrade: true
packages:
  - nginx
  - git
runcmd:
- systemctl enable nginx.service
- git clone "https://github.com/Ananyojha/test-web-page.git" web
- 'cp -r ./web/* /var/www/html/'
- systemctl restart nginx
